### ISSUE TITLE
아두이노 변경사항- 서버 전송할 데이터

### ISSUE THREAD

**Issue by suehdn** [golagola2020/hango-opensource#14]
예전에 말했던 1번 2번 이런식으로 출력하지 않고
단순하게 1, 2, 3... 12  선택되지 않으면 0을 출력해서 전송했으면 좋겠습니다.

제가 commit을 좀 이상하게 남겼네요..;;

**Comment by woorim960** [comment]
네 알겠습니다 👍 
커밋 잘 남기셨어요 ㅋㅋㅋ
